name: Update testing sing-box-ref1nd

on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:

concurrency: formula-update

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ruby .github/scripts/update-formula.rb --testing
